CREATE TABLE IF NOT EXISTS users (
	id UUID UNIQUE NOT NULL,
	name VARCHAR(256) NOT NULL,
	email VARCHAR(254) UNIQUE NOT NULL,
	password VARCHAR NOT NULL,
	created_at TIMESTAMPTZ NOT NULL,
	PRIMARY KEY(id, email)
);
