root = "."
tmp_dir = "tmp"

[build]
args_bin = []
delay = 1000
exclude_dir = []
exclude_file = []
exclude_regex = ["_test\\.go$", "\\.md$"]
exclude_unchanged = false
include_dir = ["pkg", "cmd"]
include_ext = ["go"]
include_file = []
kill_delay = "0s"
log = "/dev/stderr"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

