services:
  clickhouse:
    image: "docker.io/clickhouse/clickhouse-server:25.2.2.39.2557-alpine"
    ports:
      - 8123:8123 # HTTP interface
      - 9000:9000 # Native interface
    ulimits:
      nofile: 262144
    # healthcheck:
    #   test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
    volumes:
      - "clickhouse_data:/var/lib/clickhouse"
    environment:
      CLICKHOUSE_USER: "clickhouse"
      CLICKHOUSE_PASSWORD: "password"
      CLICKHOUSE_DB: "${PRISME_CLICKHOUSE_DB}"
    networks:
      default:
        aliases:
          - "clickhouse.localhost"

  grafana:
    image: "docker.io/grafana/grafana-oss:11.4.0"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1
      timeout: 30s
    ports:
      - 3000:3000
    user: "root:root"
    volumes:
      - "grafana_data:/data"
    environment:
      # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
      GF_INSTALL_PLUGINS: "grafana-clickhouse-datasource, mckn-funnel-panel"
      GF_LOG_LEVEL: "debug"
      # [database]
      GF_DATABASE_TYPE: "sqlite3"
      GF_DATABASE_PATH: "/data/grafana.db"
      # [users]
      GF_USERS_DEFAULT_THEME: "system"
    networks:
      default:
        aliases:
          - "grafana.localhost"

volumes:
  grafana_data:
  clickhouse_data:
