{
 "title": "General",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domains",
    "label": "Domain",
    "query": "SELECT DISTINCT(domain) FROM prisme.events_pageviews"
   },
   {
    "name": "pathnames",
    "label": "Path",
    "query": "SELECT DISTINCT(path) FROM prisme.events_pageviews\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})"
   },
   {
    "name": "operating_systems",
    "label": "Operating Systems (OS)",
    "query": "SELECT DISTINCT(operating_system) FROM prisme.events_pageviews WHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\n\n"
   },
   {
    "name": "browsers",
    "label": "Browsers",
    "query": "SELECT DISTINCT(browser_family) FROM prisme.events_pageviews WHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\n"
   },
   {
    "name": "referrals",
    "label": "Referrals",
    "query": "SELECT DISTINCT(referrer_domain) FROM prisme.events_pageviews\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\n"
   },
   {
    "name": "locations",
    "label": "Location",
    "query": "SELECT DISTINCT(country_code) as country_code FROM prisme.events_pageviews\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\n"
   },
   { "name": "sample", "label": "Sample", "query": "1, 2, 5, 10, 100, 1000" }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "stat",
   "gridPos": { "h": 5, "w": 22, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, COUNT(DISTINCT(visitor_id)) * ${sample}\nFROM \"prisme\".\"events_pageviews\"\nSAMPLE 1/${sample}\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND referrer_domain != domain\nAND country_code IN (${locations:sqlstring})\nGROUP BY time\nORDER BY time"
    },
    {
     "expression": "(${Total visitors} / ${Total visitors previous period} - 1) * 100",
     "type": "math"
    },
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, COUNT(*) * ${sample}\nFROM \"prisme\".\"events_pageviews\"\nSAMPLE 1/${sample}\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND referrer_domain != domain\nAND country_code IN (${locations:sqlstring})\nGROUP BY time\nORDER BY time\n"
    },
    {
     "expression": "(${Total visits} / ${Total visits previous period} - 1) * 100",
     "type": "math"
    },
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, COUNT(*) * ${sample}\nFROM \"prisme\".\"events_pageviews\"\nSAMPLE 1/${sample}\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND country_code IN (${locations:sqlstring})\nGROUP BY time\nORDER BY time"
    },
    {
     "expression": "100 * (${Total page views} / ${Total page views previous period}) - 100",
     "type": "math"
    },
    {
     "expression": "${Total page views} / ${Total visits}",
     "type": "math"
    },
    {
     "expression": "(${Views per visit} / ${Views per visit previous period} - 1) * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Time Series",
   "type": "timeseries",
   "description": "Number of page views over time.",
   "gridPos": { "h": 12, "w": 22, "x": 1, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "type": "stat",
   "description": "Number of visitors in the last 15 minutes.",
   "gridPos": { "h": 2, "w": 7, "x": 1, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(visitor_id)) * ${sample} AS \"Live visitors\"\nFROM prisme.events_pageviews\nSAMPLE 1/${sample}\nWHERE timestamp > subtractMinutes(now(), 15)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND country_code IN (${locations:sqlstring})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Percentage of visits that access only a single page.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "${Total number of visitors viewing a single page} / ${Total number of visitors} * 100",
     "type": "math"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Average visit duration (bounces and live visitor excluded).",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(timestamp - entry_timestamp) AS \"Visit duration\"\nFROM prisme.exit_pages_no_bounce\nWHERE $__timeFilter(timestamp)\nAND addMinutes(timestamp, 15) < now();"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Sources",
     "type": "bargauge",
     "description": "Top 10 of traffic sources.",
     "gridPos": { "h": 12, "w": 11, "x": 1, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT referrer_domain, COUNT(*) as count\nFROM \"prisme\".\"events_pageviews\"\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND country_code IN (${locations:sqlstring})\nGROUP BY referrer_domain\nORDER BY count DESC"
      }
     ]
    },
    {
     "title": "Traffic Sources",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 11, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT() AS Internal\nFROM \"prisme\".\"events_pageviews\"\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND referrer_domain = domain\nAND country_code IN (${locations:sqlstring})"
      },
      {
       "rawSql": "SELECT COUNT(*) AS Direct\nFROM \"prisme\".\"events_pageviews\"\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND referrer_domain = 'direct'\nAND country_code IN (${locations:sqlstring})"
      },
      {
       "rawSql": "SELECT COUNT(*) AS External\nFROM \"prisme\".\"events_pageviews\"\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND referrer_domain != 'direct' AND referrer_domain != domain\nAND country_code IN (${locations:sqlstring})"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Pages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Entry Pages",
     "type": "bargauge",
     "description": "Top 10 of most visited entry pages.",
     "gridPos": { "h": 13, "w": 7, "x": 1, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT path, COUNT(*) as pageviews\nFROM \"prisme\".\"entry_pages\"\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND country_code IN (${locations:sqlstring})\nGROUP BY path\nORDER BY pageviews DESC"
      }
     ]
    },
    {
     "title": "Top Pages",
     "type": "bargauge",
     "description": "Top 10 of most visited pages.",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT path, COUNT(*) as pageviews\nFROM \"prisme\".\"events_pageviews\"\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND country_code IN (${locations:sqlstring})\nGROUP BY path\nORDER BY pageviews DESC"
      }
     ]
    },
    {
     "title": "Top Exit Pages",
     "type": "bargauge",
     "description": "Top 10 of most visited exit pages (bounces excluded)",
     "gridPos": { "h": 13, "w": 7, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT path, COUNT(*) as pageviews\nFROM \"prisme\".\"exit_pages_no_bounce\"\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND country_code IN (${locations:sqlstring})\nGROUP BY path\nORDER BY pageviews DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Locations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "type": "geomap",
     "gridPos": { "h": 13, "w": 15, "x": 1, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "rawSql": "SELECT country_code, COUNT(*) as pageview\nFROM \"prisme\".\"events_pageviews\"\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND country_code IN (${locations:sqlstring})\nGROUP BY country_code\nORDER BY country_code"
      }
     ]
    },
    {
     "title": "Top Locations",
     "type": "bargauge",
     "description": "Top 10 of visitors' locations.",
     "gridPos": { "h": 13, "w": 7, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT DISTINCT(name) AS country, COUNT(*) as pageview\nFROM prisme.events_pageviews\nJOIN prisme.countries ON prisme.events_pageviews.country_code = prisme.countries.code\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND country_code IN (${locations:sqlstring})\nGROUP BY country\nORDER BY pageview DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Devices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Browsers",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 11, "x": 1, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT replaceRegexpAll(browser_family, '(.*) (Mobile|iOS)|Mobile (.*)', '\\\\1\\\\2') AS browser_family, COUNT(browser_family) as count\nFROM \"prisme\".\"events_pageviews\"\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND country_code IN (${locations:sqlstring})\nGROUP BY browser_family"
      }
     ]
    },
    {
     "title": "Operating Systems (OS)",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 11, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT operating_system, COUNT(operating_system) as count\nFROM \"prisme\".\"events_pageviews\"\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND country_code IN (${locations:sqlstring})\nGROUP BY operating_system"
      }
     ]
    }
   ]
  },
  {
   "title": "Custom Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Custom Events",
     "type": "bargauge",
     "description": "Top 10 of most sent custom events.",
     "gridPos": { "h": 13, "w": 11, "x": 1, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT name, COUNT(*) as count\nFROM \"prisme\".\"events_custom\"\nWHERE $__timeFilter(timestamp)\nAND domain IN (${domains:sqlstring})\nAND path IN (${pathnames:sqlstring})\nAND operating_system IN (${operating_systems:sqlstring})\nAND browser_family IN (${browsers:sqlstring})\nAND referrer_domain IN (${referrals:sqlstring})\nAND country_code IN (${locations:sqlstring})\nGROUP BY name\nORDER BY count DESC\n"
      }
     ]
    }
   ]
  }
 ]
}