package faker

var (
	CountryCodesList = []string{
		"AF", "AX", "AL", "DZ", "AS", "AD", "AO", "AI", "AQ", "AG", "AR", "AM", "AW",
		"AU", "AT", "AZ", "BS", "BH", "BD", "BB", "BY", "BE", "BZ", "BJ", "BM", "BT",
		"BO", "BQ", "BA", "BW", "BV", "BR", "IO", "BN", "BG", "BF", "BI", "CV",
		"KH", "CM", "CA", "KY", "CF", "TD", "CL", "CN", "CX", "CC", "CO", "KM", "CD",
		"CG", "CK", "CR", "CI", "HR", "CU", "CW", "CY", "CZ", "DK", "DJ", "DM", "DO",
		"EC", "EG", "SV", "GQ", "ER", "EE", "SZ", "ET", "FK", "FO", "FJ", "FI", "FR",
		"GF", "PF", "TF", "GA", "GM", "GE", "DE", "GH", "GI", "GR", "GL", "GD", "GP",
		"GU", "GT", "GG", "GN", "GW", "GY", "HT", "HM", "VA", "HN", "HK", "HU", "IS",
		"IN", "ID", "IR", "IQ", "IE", "IM", "IL", "IT", "JM", "JP", "JE", "JO", "KZ",
		"KE", "KI", "KP", "KR", "KW", "KG", "LA", "LV", "LB", "LS", "LR", "LY", "LI",
		"LT", "LU", "MO", "MG", "MW", "MY", "MV", "ML", "MT", "MH", "MQ", "MR", "MU",
		"YT", "MX", "FM", "MD", "MC", "MN", "ME", "MS", "MA", "MZ", "MM", "NA", "NR",
		"NP", "NL", "NC", "NZ", "NI", "NE", "NG", "NU", "NF", "MK", "MP", "NO", "OM",
		"PK", "PW", "PS", "PA", "PG", "PY", "PE", "PH", "PN", "PL", "PT", "PR", "QA",
		"RE", "RO", "RU", "RW", "BL", "SH", "KN", "LC", "MF", "PM", "VC", "WS", "SM",
		"ST", "SA", "SN", "RS", "SC", "SL", "SG", "SX", "SK", "SI", "SB", "SO", "ZA",
		"GS", "SS", "ES", "LK", "SD", "SR", "SJ", "SE", "CH", "SY", "TW", "TJ", "TZ",
		"TH", "TL", "TG", "TK", "TO", "TT", "TN", "TR", "TM", "TC", "TV", "UG", "UA",
		"AE", "GB", "UM", "US", "UY", "UZ", "VU", "VE", "VN", "VG", "VI", "WF", "EH",
		"YE", "ZM", "ZW", "XX",
	}
	DomainList = []string{
		"app.prismeanalytics.com", "caddyserver.com", "clickhouse.com", "dart.dev",
		"datatracker.ietf.org", "dev.to", "developer.mozilla.org", "docker.com",
		"docs.docker.com", "en.cppreference.com", "en.wikipedia.org",
		"fonts.googleapis.com", "github.com", "github.com", "go.dev", "grafana.com",
		"gravatar.com", "www.w3.org", "hub.docker.com", "jakearchibald.github.io",
		"jsr.io", "nginx.org", "opensource.org", "prisme.features.vote",
		"royal.pingdom.com", "rsms.me", "schema.org", "source.chromium.org",
		"squoosh.app", "stripe.com", "traefik.io", "www.bulkcompress.photos",
		"www.buymeacoffee.com", "www.freecodecamp.org", "www.libvips.org",
		"www.linkedin.com", "www.negrel.dev", "www.prismeanalytics.com",
		"www.reddit.com", "www.rfc-editor.org", "www.sirene.fr",
		"www.websitecarbon.com", "x.com",
		"youtube.com", "www.google.com", "www.blogger.com", "cloudflare.com",
		"apple.com", "linkedin.com", "googleusercontent.com", "support.google.com",
		"docs.google.com", "microsoft.com", "wordpress.org", "whatsapp.com",
		"maps.google.com", "play.google.com", "en.wikipedia.org", "plus.google.com",
		"sites.google.com", "accounts.google.com", "t.me", "europa.eu",
		"bp.blogspot.com", "youtu.be", "drive.google.com", "mozilla.org", "vk.com",
		"adobe.com", "facebook.com", "vimeo.com", "uol.com.br",
		"policies.google.com", "g.page", "istockphoto.com", "amazon.com",
		"github.com", "paypal.com", "tiktok.com", "tools.google.com",
		"brandbucket.com", "ok.ru", "gravatar.com", "wikimedia.org",
		"news.google.com", "opera.com", "dropbox.com", "feedburner.com",
		"netvibes.com", "files.wordpress.com", "draft.blogger.com",
		"googleblog.com", "myspace.com",
	}
	PathList = []string{
		"/", "/@negrel/webpush", "/BreadcrumbList", "/ListItem", "/authn/sign_in",
		"/authn/sign_up", "/blog/", "/blog/",
		"/blog/building-an-online-image-compressor/",
		"/blog/deno-web-push-notifications/", "/blog/generate",
		"/blog/mastering-funnel-analysis/", "/blog/measuring-ctr-linkedin-traffic/",
		"/blog/measuring-ctr-x-twitter-traffic/", "/blog/prisme-0.14-release/",
		"/blog/prisme-0.15-release/", "/blog/prisme-0.16-release/",
		"/blog/prisme-0.17-0.18-release/", "/blog/understanding-utm-parameters/",
		"/blog/zero-cost-debug-assertions-in-go/", "/board",
		"/chromium/chromium/src/+/main%3Athird_party/blink/renderer/core/offscreencanvas/offscreen_canvas.cc;l=193;drc=e5f8ff312fe542f39c7d34b4440f18d1500b15f9",
		"/chromium/chromium/src/+/main%3Athird_party/blink/renderer/platform/graphics/image_data_buffer.cc;drc=e5f8ff312fe542f39c7d34b4440f18d1500b15f9;bpv=1;bpt=1;l=143?gsn=EncodeImageInternal&gs=KYTHE://KoQDCr8Ba3l0aGU6Ly9jaHJvbWl1bS5nb29nbGVzb3VyY2UuY29tL2NvZGVzZWFyY2gvY2hyb21pdW0vc3JjLy9tYWluP2xhbmc9YyUyQiUyQj9wYXRoPXRoaXJkX3BhcnR5L2JsaW5rL3JlbmRlcmVyL3BsYXRmb3JtL2dyYXBoaWNzL2ltYWdlX2RhdGFfYnVmZmVyLmNjIzZCU3paMGhFTHExSzBGU1BpNWVsLThRbThfM2N5TW40aEI4UElCeGswdVEKvwFreXRoZTovL2Nocm9taXVtLmdvb2dsZXNvdXJjZS5jb20vY29kZXNlYXJjaC9jaHJvbWl1bS9zcmMvL21haW4_bGFuZz1jJTJCJTJCP3BhdGg9dGhpcmRfcGFydHkvYmxpbmsvcmVuZGVyZXIvcGxhdGZvcm0vZ3JhcGhpY3MvaW1hZ2VfZGF0YV9idWZmZXIuY2MjaVp3MmxuTW5vSDhjaDJPQmk5QmpMU0VpanN5OWk5XzRMcncwd0pJSjlHOA%3D%3D",
		"/clickhouse-icon.svg", "/company/prisme-analytics/", "/compose/install/",
		"/contact/", "/css2", "/doc/html/rfc8292", "/docs/", "/docs/0.15/",
		"/docs/en/engines/table-engines/mergetree-family/versionedcollapsingmergetree",
		"/docs/en/sql-reference/data-types/uuid",
		"/docs/en/sql-reference/functions/json-functions",
		"/docs/en/sql-reference/functions/type-conversion-functions",
		"/docs/guides/create-a-custom-dashboard/",
		"/docs/guides/exclude-your-own-visits/", "/docs/guides/overview/",
		"/docs/guides/self-host-prisme-docker/",
		"/docs/guides/setup-tracking-script/", "/docs/guides/track-scroll-depth/",
		"/docs/next/",
		"/docs/next/guides/create-a-custom-dashboard/",
		"/docs/next/guides/exclude-your-own-visits/",
		"/docs/next/guides/overview/", "/docs/next/guides/self-host-prisme-docker/",
		"/docs/next/guides/setup-tracking-script/",
		"/docs/next/guides/track-scroll-depth/",
		"/docs/next/references/admin-metrics/", "/docs/next/references/clickhouse/",
		"/docs/next/references/glossary/", "/docs/next/references/http/",
		"/docs/next/references/server/default-mode/",
		"/docs/next/references/server/ingestion-mode/",
		"/docs/next/references/server/server-modes/",
		"/docs/next/references/tracking-script/",
		"/docs/next/references/web-analytics-dashboard/",
		"/docs/references/admin-metrics/", "/docs/references/clickhouse/",
		"/docs/references/clickhouse/",
		"/docs/references/http/",
		"/docs/references/http/",
		"/docs/references/server/default-mode/",
		"/docs/references/server/ingestion-mode/",
		"/docs/references/server/server-modes/",
		"/docs/references/tracking-script/",
		"/docs/references/tracking-script/",
		"/docs/references/web-analytics-dashboard/",
		"/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL",
		"/en-US/docs/Learn/HTML/Howto/Use_data_attributes",
		"/en-US/docs/Web/API/Document/scroll_event",
		"/en-US/docs/Web/API/Document/scrollend_event",
		"/en-US/docs/Web/API/Document/visibilitychange_event",
		"/en-US/docs/Web/API/HTMLAnchorElement/ping", "/en-US/docs/Web/API/History",
		"/en-US/docs/Web/API/History/pushState",
		"/en-US/docs/Web/API/Location/host",
		"/en-US/docs/Web/API/Location/pathname",
		"/en-US/docs/Web/API/PushManager/subscribe",
		"/en-US/docs/Web/API/PushSubscription", "/en-US/docs/Web/API/Push_API",
		"/en-US/docs/Web/API/Service_Worker_API", "/en-US/docs/Web/API/URL/origin",
		"/en-US/docs/Web/API/Window",
		"/en-US/docs/Web/API/Window/beforeunload_event",
		"/en-US/docs/Web/HTML/Element/a",
		"/en-US/docs/Web/HTTP/Headers/Origin",
		"/en-US/docs/Web/HTTP/Headers/Referer",
		"/en-US/docs/Web/HTTP/Headers/Sec-CH-UA-Platform",
		"/en-US/docs/Web/HTTP/Headers/User-Agent",
		"/en-US/docs/Web/HTTP/Headers/X-Forwarded-For",
		"/en-US/docs/Web/HTTP/Status/429", "/engine/install/",
		"/feedback/", "/feedback/",
		"/grafana", "/grafana/",
		"/grafana/d/eegq2vj9n7bb4c/web-analytics?orgId=5&kiosk=&from=now-7d&to=now&timezone=browser",
		"/grafana/d/f8278729-d6bd-49ec-be92-abf01917f14d/web-analytics?orgId=5&kiosk",
		"/grid.svg", "/image-experiments/channels/",
		"/is/lightweight-analytics/",
		"/is/open-source-website-analytics/",
		"/is/privacy-focused-analytics/",
		"/is/progressive-analytics/",
		"/is/simple-analytics/",
		"/language/error-handling",
		"/libvips/libvips/wiki/Why-is-libvips-quick",
		"/license/agpl-v3",
		"/logo.svg",
		"/negrel",
		"/negrel.assert",
		"/negrel/bulkcompress.photos",
		"/negrel/cutelink",
		"/negrel/http-ece",
		"/negrel/paon",
		"/negrel/ringo",
		"/negrel/webpush",
		"/negrel_dev",
		"/news/how-jpg-works-a4dbd2316f35/",
		"/osd",
		"/page-load-time-really-affect-bounce-rate/",
		"/prismeanalytics",
		"/prismelabs/analytics",
		"/prismelabs/analytics/blob/master/LICENSE",
		"/prismelabs/analytics/blob/master/tracker",
		"/prismelabs/analytics/blob/v0.15.0/deploy/docker-compose.yml",
		"/prismelabs/analytics/releases/tag/v0.14.0",
		"/prismelabs/analytics/releases/tag/v0.15.0",
		"/prismelabs/analytics/releases/tag/v0.16.0",
		"/prismelabs/analytics/releases/tag/v0.17.0",
		"/prismelabs/analytics/releases/tag/v0.18.0",
		"/privacy/",
		"/r/SideProject/comments/18u925v/i_made_a_tool_in_2_hours_it_made_me_1000_so_far",
		"/r/prismelabs/analytics",
		"/rfc/rfc8291",
		"/silvia-odwyer/photon",
		"/sirene/public/accueil",
		"/sitemap.xml",
		"/sitemap.xml",
		"/stretchr/testify",
		"/styles/blogpost.css",
		"/styles/blogpost.css",
		"/styles/index.css",
		"/styles/index.css",
		"/styles/syntax-highlight.css",
		"/styles/syntax-highlight.css",
		"/terms/",
		"/tools/ctr_calculator/",
		"/tools/url_shortener/",
		"/tools/utm_builder/",
		"/traefik",
		"/trentm/node-bunyan",
		"/vs/google-analytics/",
		"/vs/matomo/",
		"/w/cpp/error/assert",
		"/wiki/Chrominance",
		"/wiki/ISO_3166-1_alpha-2",
		"/wiki/JPEG",
		"/wiki/List_of_web_analytics_software",
		"/wiki/Quantization_(image_processing)",
		"/wiki/Server-sent_events",
		"/wiki/UTM_parameters",
		"/wiki/Web_analytics",
	}
)
