services:
  prisme:
    image: "docker.io/prismelabs/analytics:v0.17.0"
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      # Configuration options are listed and explained here:
      # https://www.prismeanalytics.com/docs/set-up/configuration/configure-server/default-mode
      #
      PRISME_ACCESS_LOG: '/dev/stdout'
      PRISME_DEBUG: 'false'
      PRISME_PORT: '8000'
      PRISME_TRUST_PROXY: 'false'
      PRISME_CLICKHOUSE_TLS: 'false'
      PRISME_CLICKHOUSE_HOSTPORT: 'clickhouse.localhost:9000'
      PRISME_CLICKHOUSE_USER: 'default'
      PRISME_CLICKHOUSE_PASSWORD: 'password'
      PRISME_CLICKHOUSE_DB: 'prisme'
      PRISME_SOURCE_REGISTRY_SOURCES: 'localhost,mywebsite.localhost,foo.mywebsite.localhost'
      PRISME_GRAFANA_URL: 'http://grafana.localhost:3000'
      PRISME_GRAFANA_USER: 'admin'
      PRISME_GRAFANA_PASSWORD: 'admin'

  clickhouse:
    image: "clickhouse/clickhouse-server:25.8.1.5101-alpine"
    ports:
      - 127.0.0.1:8123:8123 # HTTP interface (useful for debugging)
      - 127.0.0.1:9000:9000 # Native interface (used by Prisme instances)
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8123/ping || exit 1
    volumes:
      - "clickhouse_data:/var/lib/clickhouse"
    environment:
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "password"
      CLICKHOUSE_DB: "prisme"
    networks:
      default:
        aliases:
          - "clickhouse.localhost"

volumes:
  clickhouse_data:

