// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package full

import (
	"github.com/prismelabs/prismeanalytics/cmd/server/wired"
	"github.com/prismelabs/prismeanalytics/pkg/clickhouse"
	"github.com/prismelabs/prismeanalytics/pkg/grafana"
	"github.com/prismelabs/prismeanalytics/pkg/handlers"
	"github.com/prismelabs/prismeanalytics/pkg/middlewares"
	"github.com/prismelabs/prismeanalytics/pkg/services/eventstore"
	grafana2 "github.com/prismelabs/prismeanalytics/pkg/services/grafana"
	"github.com/prismelabs/prismeanalytics/pkg/services/ipgeolocator"
	"github.com/prismelabs/prismeanalytics/pkg/services/sourceregistry"
	"github.com/prismelabs/prismeanalytics/pkg/services/uaparser"
)

// Injectors from wire.go:

func Initialize(logger wired.BootstrapLogger) wired.App {
	server := wired.ProvideServerConfig(logger)
	eventsCors := middlewares.ProvideEventsCors()
	eventsRateLimiter := middlewares.ProvideEventsRateLimiter(server)
	logLogger := wired.ProvideLogger(server)
	accessLog := middlewares.ProvideAccessLog(server, logLogger)
	errorHandler := middlewares.ProvideErrorHandler()
	healhCheck := handlers.ProvideHealthCheck()
	middlewaresLogger := middlewares.ProvideLogger(logLogger)
	requestId := middlewares.ProvideRequestId(server)
	static := middlewares.ProvideStatic(server)
	minimalFiber := wired.ProvideMinimalFiber(accessLog, server, errorHandler, healhCheck, middlewaresLogger, requestId, static)
	configClickhouse := wired.ProvideClickhouseConfig(logger)
	ch := clickhouse.ProvideCh(logLogger, configClickhouse)
	service := eventstore.ProvideClickhouseService(ch, logLogger)
	sourceregistryService := sourceregistry.ProvideEnvVarService(logLogger)
	uaparserService := uaparser.ProvideService()
	ipgeolocatorService := ipgeolocator.ProvideMmdbService(logLogger)
	postPageViewEvent := handlers.ProvidePostEventsPageViews(service, sourceregistryService, uaparserService, ipgeolocatorService)
	app := ProvideFiber(eventsCors, eventsRateLimiter, minimalFiber, postPageViewEvent)
	configGrafana := wired.ProvideGrafanaConfig(logger)
	client := grafana.ProvideClient(configGrafana)
	grafanaService := grafana2.ProvideService(client, configClickhouse)
	setup := ProvideSetup(logLogger, client, grafanaService)
	wiredApp := wired.ProvideApp(server, app, logLogger, setup)
	return wiredApp
}
