// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/prismelabs/prismeanalytics/internal/handlers"
	"github.com/prismelabs/prismeanalytics/internal/middlewares"
	"github.com/prismelabs/prismeanalytics/internal/postgres"
	"github.com/prismelabs/prismeanalytics/internal/services/auth"
	"github.com/prismelabs/prismeanalytics/internal/services/orgs"
	"github.com/prismelabs/prismeanalytics/internal/services/sessions"
	"github.com/prismelabs/prismeanalytics/internal/services/users"
)

// Injectors from wire.go:

func initialize(logger BootstrapLogger) App {
	config := ProvideConfig(logger)
	views := ProvideFiberViewsEngine(config)
	logLogger := ProvideLogger(config)
	middlewaresLogger := middlewares.ProvideLogger(logLogger)
	server := config.Server
	accessLog := middlewares.ProvideAccessLog(server, logLogger)
	requestId := middlewares.ProvideRequestId(server)
	static := middlewares.ProvideStatic(server)
	service := sessions.ProvideService()
	withSession := middlewares.ProvideWithSession(service)
	favicon := middlewares.ProvideFavicon()
	notFound := middlewares.ProvideNotFound()
	getSignUp := handlers.ProvideGetSignUp()
	configPostgres := config.Postgres
	pg := postgres.ProvidePg(logLogger, configPostgres)
	usersService := users.ProvideService(pg)
	postSignUp := handlers.ProvidePostSignUp(usersService, service)
	getSignIn := handlers.ProvideGetSignIn()
	authService := auth.ProvideService(usersService)
	postSignIn := handlers.ProvidePostSignIn(authService, service)
	orgsService := orgs.ProvideService(pg)
	getIndex := handlers.ProvideGetIndex(orgsService)
	handlersNotFound := handlers.ProvideNotFound()
	getOrgsNew := handlers.ProvideGetOrgsNew()
	postOrgsNew := handlers.ProvidePostOrgsNew(orgsService)
	getOrgsOrgId := handlers.ProvideGetOrgsOrgId(orgsService)
	app := ProvideFiber(config, views, middlewaresLogger, accessLog, requestId, static, withSession, favicon, notFound, getSignUp, postSignUp, getSignIn, postSignIn, getIndex, handlersNotFound, getOrgsNew, postOrgsNew, getOrgsOrgId)
	mainApp := ProvideApp(config, app, logLogger)
	return mainApp
}
