name: release
on:
  release:
    types: ["published"]
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v24
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: printenv
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
      - uses: dawidd6/action-download-artifact@v3
        with:
          name: docker-image
          workflow: push.yaml
      - run: docker load < result
      - name: Publish server to docker hub
        run: |
          set -x;
          for tag in $(.github/scripts/tags.sh $GITHUB_REF_NAME); do
          docker tag "prismelabs/analytics:dev" "docker.io/prismelabs/analytics:$tag"
            docker push "docker.io/prismelabs/analytics:$tag"
          done


